// PRODUCT TYPES
export const GET_PRODUCT_COUNT_REQUEST = "GET_PRODUCT_COUNT_REQUEST";
export const GET_PRODUCT_COUNT_SUCCESS = "GET_PRODUCT_COUNT_SUCCESS";
export const GET_PRODUCT_COUNT_FAIL = "GET_PRODUCT_COUNT_FAIL";

export const GET_USERS_COUNT_REQUEST = "GET_USERS_COUNT_REQUEST";
export const GET_USERS_COUNT_SUCCESS = "GET_USERS_COUNT_SUCCESS";
export const GET_USERS_COUNT_FAIL = "GET_USERS_COUNT_FAIL";

export const GET_TOTAL_ERNINGS_COUNT_REQUEST =
  "GET_TOTAL_ERNINGS_COUNT_REQUEST";
export const GET_TOTAL_ERNINGS_COUNT_SUCCESS =
  "GET_TOTAL_ERNINGS_COUNT_SUCCESS";
export const GET_TOTAL_ERNINGS_COUNT_FAIL = "GET_TOTAL_ERNINGS_COUNT_FAIL";

export const GET_ORDERS_COUNT_REQUEST = "GET_ORDERS_COUNT_REQUEST";
export const GET_ORDERS_COUNT_SUCCESS = "GET_ORDERS_COUNT_SUCCESS";
export const GET_ORDERS_COUNT_FAIL = "GET_ORDERS_COUNT_FAIL";

//AUTH TYPES

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const USER_REQUEST = "USER_REQUEST";
export const USER_LOADED = "USER_LOADED";
export const USER_FAIL = "USER_FAIL";
