export const GET_PRODUCT_COUNT_REQUEST = "GET_PRODUCT_COUNT_REQUEST";
export const GET_PRODUCT_COUNT_SUCCESS = "GET_PRODUCT_COUNT_SUCCESS";
export const GET_PRODUCT_COUNT_FAIL = "GET_PRODUCT_COUNT_FAIL";
